### ISSUE TITLE
CSS Modules can't refers other files within the compose folder

### ISSUE THREAD

**Issue by MatteoGabriele** [Blocklevel/blue-next#58]
**It works only if the link in a.css to b.css is relative** 

example

**this is the current behavior and doesn't work**

`component/home/home.css`

```css
.button {
  composes: classFromA from $a;
}
```

`compose/a.css`

```css
.classFromA {
  composes: classFromB from $b;
}
```

`compose/b.css`

```css
.classFromB {
  color: red;
}
```

---  

**this example works**

`component/home/home.css`

```css
.button {
  composes: classFromA from $a;
}
```

`compose/a.css`

```css
.classFromA {
  composes: classFromB from './b.css';
}
```

`compose/b.css`

```css
.classFromB {
  color: red;
}
```
